version: '3'
services:
  k-caldera:
    build:
      context: .
      dockerfile: ./Dockerfile
      network: host
    container_name: k-caldera
    ports:
      - 8000:8000
      - 5000:5000
    volumes:
      - /dev/shm:/dev/shm
      - ./config:/usr/src/app/config
